name: metrics
description: genertate metrics
author: moses

inputs: 
  token: 
    description:
    required:

  outputDir:
      description: output directory
      required: true
      default: ${{ github.workspace }}
  
  octokit_max_retries:
    description: maximum number if retries 
    required: true
    default: 15
  
  since:
    description: A date time in format YYYY-MM-DDTHH:mm:ss. If specified activity_days will be ignored.
    required: false

  activity_days:
    description: The number of days in the past to check for activity, this will be ignored if 'since' parameter is used.
    required: true
    default: 30
  
runs:
  using: node12
  main: dist/index.js